/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Helper;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author pared
 */
public class AlquilerAutos extends javax.swing.JDialog {

    /**
     * Creates new form AlquilerAutos
     * @param parent
     * @param modal
     */
    String ruta;
    public AlquilerAutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ruta = "src/datos/autosAlquilados.txt";
        Helper.llenarTablaAlquilar(tblTablaAlquilar, ruta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbAlquilar1 = new javax.swing.JButton();
        cmbAlquilar2 = new javax.swing.JButton();
        cmbAlquilar3 = new javax.swing.JButton();
        cmbAlquilar4 = new javax.swing.JButton();
        cmbAlquilar5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTablaAlquilar = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbAlquilar1.setText("Alquilar");
        cmbAlquilar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAlquilar1ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbAlquilar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        cmbAlquilar2.setText("Alquilar");
        cmbAlquilar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAlquilar2ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbAlquilar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, -1, -1));

        cmbAlquilar3.setText("Alquilar");
        cmbAlquilar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAlquilar3ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbAlquilar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 110, -1, -1));

        cmbAlquilar4.setText("Alquilar");
        cmbAlquilar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAlquilar4ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbAlquilar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        cmbAlquilar5.setText("Alquilar");
        cmbAlquilar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAlquilar5ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbAlquilar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 360, -1, -1));

        tblTablaAlquilar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Cedula", "Automovil", "Fecha", "Horas Alquiladas", "Dinero a Pagar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTablaAlquilar);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 990, 170));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Captura5.PNG"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 330, 200));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Captura1.PNG"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 210));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Captura2.PNG"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 340, 210));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Captura4.PNG"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 310, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/descarga (2).jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/descarga (3).jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 290, 190));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/descarga (4).jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 280, 190));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/6355918990223938941737718871_giphy.gif"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 500, 320));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/183903088.gif"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 500, 340));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/descarga (2).jpg"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 290, 130, 200));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/noche.gif"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 500, 250));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tumblr_m9ychoruds1r3055wo1_500.gif"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, -1, 250));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/descarga (4).jpg"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 490, 150, 260));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Captura.PNG"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 320, 210));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/descarga (7).jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 300, 180));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAlquilar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlquilar1ActionPerformed
         
        DatosAlquilados a = new DatosAlquilados(null,true,tblTablaAlquilar);
        
        DatosAlquilados.txtAutomovil.setText("Wolkswagen");
        DatosAlquilados.txtSerie.setText("Gol Power 1.4");
        DatosAlquilados.txtPrecioAlquilar.setText("300000");
        
        a.setVisible(true);
            
    }//GEN-LAST:event_cmbAlquilar1ActionPerformed

    private void cmbAlquilar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlquilar2ActionPerformed
        DatosAlquilados a = new DatosAlquilados(null,true,tblTablaAlquilar);
        
        DatosAlquilados.txtAutomovil.setText("Renault");
        DatosAlquilados.txtSerie.setText("Logan Authentique");
        DatosAlquilados.txtPrecioAlquilar.setText("200000");
        
            a.setVisible(true);
    }//GEN-LAST:event_cmbAlquilar2ActionPerformed

    private void cmbAlquilar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlquilar3ActionPerformed
        DatosAlquilados a = new DatosAlquilados(null,true,tblTablaAlquilar);
        
        DatosAlquilados.txtAutomovil.setText("Audi");
        DatosAlquilados.txtPrecioAlquilar.setText("400000");
        
            a.setVisible(true);
    }//GEN-LAST:event_cmbAlquilar3ActionPerformed

    private void cmbAlquilar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlquilar4ActionPerformed
        DatosAlquilados a = new DatosAlquilados(null,true,tblTablaAlquilar);
        
        DatosAlquilados.txtAutomovil.setText("Siena");
        DatosAlquilados.txtSerie.setText("EL 1.4 Attractive");
        DatosAlquilados.txtPrecioAlquilar.setText("250000");
        
            a.setVisible(true);
    }//GEN-LAST:event_cmbAlquilar4ActionPerformed

    private void cmbAlquilar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlquilar5ActionPerformed
        DatosAlquilados a = new DatosAlquilados(null,true,tblTablaAlquilar);
        
        DatosAlquilados.txtAutomovil.setText("Nissan");
        DatosAlquilados.txtSerie.setText("Levina");
        DatosAlquilados.txtPrecioAlquilar.setText("300000");
        
        a.setVisible(true);
    }//GEN-LAST:event_cmbAlquilar5ActionPerformed

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        Volkswagen v = new Volkswagen(null, true);
         v.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
       Renault r = new Renault(null, true);
         r.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        Livina l = new Livina(null, true);
         l.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        Siena s = new Siena(null, true);
        s.setVisible(true);
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        Auto3 b = new Auto3(null, true);
        b.setVisible(true);
    }//GEN-LAST:event_jLabel16MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlquilerAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlquilerAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlquilerAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlquilerAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AlquilerAutos dialog = new AlquilerAutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbAlquilar1;
    private javax.swing.JButton cmbAlquilar2;
    private javax.swing.JButton cmbAlquilar3;
    private javax.swing.JButton cmbAlquilar4;
    private javax.swing.JButton cmbAlquilar5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTablaAlquilar;
    // End of variables declaration//GEN-END:variables
}
