/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz;

import clases.Autos;
import clases.AutosUsados;
import clases.Helper;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author jparedes2
 */
public class AutosNuevos extends javax.swing.JDialog {
    /**
     * Creates new form AutosNuevos
     */
         String ruta;
        ObjectOutputStream salida;
        ArrayList<Autos> auto;
    public AutosNuevos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       ruta = "src/datos/autos.txt";
       JButton botonesH[]={cmbListar};
        JButton botonesD[]={cmbComprar,cmbEliminar};
        
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAutosNuevos = new javax.swing.JTable();
        cmbMarca = new javax.swing.JComboBox();
        cmbListar = new javax.swing.JButton();
        cmbComprar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblAutosNuevos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Tipo Marca", "Modelo", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAutosNuevos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAutosNuevosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAutosNuevos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 340, 220));

        cmbMarca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbMarca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chevrolet", "Ford", "Renault", "Nissan", "Mazda", "Audi", "Ferrari", "Lamborghini", " " }));
        cmbMarca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMarcaItemStateChanged(evt);
            }
        });
        cmbMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMarcaActionPerformed(evt);
            }
        });
        jPanel1.add(cmbMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 100, 30));

        cmbListar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbListar.setText("Listar");
        cmbListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbListarActionPerformed(evt);
            }
        });
        jPanel1.add(cmbListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 100, 30));

        cmbComprar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbComprar.setText("Comprar");
        cmbComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbComprarActionPerformed(evt);
            }
        });
        jPanel1.add(cmbComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 100, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("AUTOMOVILES NUEVOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 290, 40));

        cmbEliminar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbEliminar.setText("Eliminar");
        cmbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(cmbEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 100, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/noche.gif"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 500, 280));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/6355918990223938941737718871_giphy.gif"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 500, 320));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/6355918990223938941737718871_giphy.gif"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 510, 310));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 560, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbListarActionPerformed
        String marca =cmbMarca.getSelectedItem().toString();
        Helper.listadoPorMarca(tblAutosNuevos, ruta, marca);
        
        JButton botonesH[]={cmbComprar, cmbEliminar, cmbListar};
        JButton botonesD[]={};
        
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmbListarActionPerformed

    private void cmbMarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMarcaItemStateChanged
        String marca =cmbMarca.getSelectedItem().toString();
        Helper.listadoPorMarca(tblAutosNuevos, ruta, marca);
    }//GEN-LAST:event_cmbMarcaItemStateChanged

    private void cmbComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbComprarActionPerformed
          int op, i, fila;
          op = JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea comprar este coche?", "Eliminar", JOptionPane.YES_NO_OPTION);
          
          ArrayList<Autos> auto = Helper.traerDatos(ruta);
          if (op == JOptionPane.YES_OPTION){
              CompradoresAutos a = new CompradoresAutos(null, true);
                
              fila = tblAutosNuevos.getSelectedRow();
              
              CompradoresAutos.txtMarca.setText(tblAutosNuevos.getValueAt(fila, 0).toString());
              CompradoresAutos.txtModelo.setText(tblAutosNuevos.getValueAt(fila, 2).toString());
            
              a.show();
          }
    }//GEN-LAST:event_cmbComprarActionPerformed

    private void tblAutosNuevosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAutosNuevosMouseClicked

        
    }//GEN-LAST:event_tblAutosNuevosMouseClicked

    private void cmbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEliminarActionPerformed
        int i, op;
        op = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar a este auto?", "Eliminar", JOptionPane.YES_NO_OPTION);

        ArrayList<Autos> auto = Helper.traerDatos(ruta);
        if (op == JOptionPane.YES_OPTION) {
            i = tblAutosNuevos.getSelectedRow();
            auto.remove(i);
            try {
                salida = new ObjectOutputStream(new FileOutputStream(ruta));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(AgregarAutosUsados.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(AgregarAutosUsados.class.getName()).log(Level.SEVERE, null, ex);
            }
            Helper.volcado(salida, auto);
            Helper.llenarTablaAutosUsados(tblAutosNuevos, ruta);
            cmbMarca.setSelectedIndex(0);
        }
        JButton botonesH[]={cmbListar,cmbComprar, cmbEliminar};
        JButton botonesD[]={};
        
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmbEliminarActionPerformed

    private void cmbMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMarcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutosNuevos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutosNuevos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutosNuevos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutosNuevos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AutosNuevos dialog = new AutosNuevos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbComprar;
    private javax.swing.JButton cmbEliminar;
    private javax.swing.JButton cmbListar;
    private javax.swing.JComboBox cmbMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAutosNuevos;
    // End of variables declaration//GEN-END:variables
}
